require 'test_helper'

class SiteLayoutTest < ActionDispatch::IntegrationTest
  test "layout links" do
    get root_path
    assert_template 'static_pages/home'
    assert_select "a[href=?]", root_path, count: 2
    assert_select "a[href=?]", helping_path
    assert_select "a[href=?]", about_path
    assert_select "a[href=?]", contact_path
    # Tests that each link appears on page generated by root path. Tests that link to root path appears twice
    get contact_path
    assert_select "title", full_title("Contact")
  end
end
