require 'test_helper'

class SiteLayoutTest < ActionDispatch::IntegrationTest
  def setup
    @user = users(:daniel)
    @user_two = users(:michelle)
  end

  test "layout links" do
    get root_path
    assert_template 'static_pages/home'
    assert_select "a[href=?]", root_path, count: 2
    assert_select "a[href=?]", helping_path
    assert_select "a[href=?]", about_path
    assert_select "a[href=?]", contact_path
    # Tests that each link appears on page generated by root path. Tests that link to root path appears twice
    get contact_path
    assert_select "title", full_title("Contact")
    get helping_path
    assert_select "title", full_title("Help")
    get about_path
    assert_select "title", full_title("About")
    get users_path
    assert_redirected_to login_path
    get edit_user_path(@user)
    assert_redirected_to login_path
    get user_path(@user)
    assert_template 'users/show'
    login_as(@user)
    get users_path
    assert_template 'users/index'
    get edit_user_path(@user)
    assert_template 'users/edit'
    get edit_user_path(@user_two)
    assert_redirected_to root_path
  end
end
